version: "3"

services:
  mydb:
    container_name: mydb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: yogesh123
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - datastore

  be-app:
    container_name: be-app
    build:
      context: ../
      dockerfile: Dockerfile
      args:
        TAG: compose-v1
    environment:
      MYSQL_HOST: "jdbc:mysql://mydb:3306/datastore?createDatabaseIfNotExist=true"
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: yogesh123
    links:
      - mydb
    depends_on:
      mydb:
        condition: service_healthy
    networks:
      - datastore

  fe-app:
    container_name: fe-app
    build:
      context: ../../../DataStoreFront/DataStoreFront
      +dockerfile: Dockerfile-frontend
      args:
        TAG: compose-v1
    environment:
      API_URL: http://be-app:8084
    links:
      - be-app
    ports:
      - "8585:8080"
    depends_on:
      - be-app
    networks:
      - datastore

networks:
  datastore:
    driver: bridge
